name: Sample workflow
on:
 push:
  branches:
   - master
jobs:
 demo:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout code
     uses: actions/checkout@v4.2.2
   - name: display a success page
     run: echo "Welcome to Github Actions"
   - name: display the present working directory
     run: 
      pwd
      ls
   - name: Setup Java JDK
     uses: actions/setup-java@v4.6.0
     
   
    

     
   
