name: Sample workflow
on:
 push:
  branches:
   - master
jobs:
 demo:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout code
     uses: actions/checkout@v4.2.2
   - name: display a success page
     uses: echo "Welcome to Github Actions"

     
   
